### PR TITLE
Add support for uploads over remote (telnet) console

### PR DESCRIPTION
**Pull request by trisk**

### CODE REVIEW

**Comment by 4refr0nt** [comment]
Hi!
Please wait some days when I test this feature.

**Comment by kmpm** [comment]
do you have the source of the telnet server somewhere?
So that I can test things.

**Comment by trisk** [comment]
See:
https://github.com/trisk/nodemcu-scripts/blob/master/common/telnet.lua or https://github.com/trisk/nodemcu-scripts/blob/master/common/server.lua

**Comment by trisk** [comment]
The example that comes with NodeMCU should also work: https://github.com/nodemcu/nodemcu-firmware/blob/master/examples/telnet.lua

**Comment by 4refr0nt** [comment]
This branch has conflicts that must be resolved

**Pull request closed without merging**
