### PR TITLE
Add support to connect to a module via TCP & telnet server

### PR DESCRIPTION
**Pull request by shing19m**
Add a lua telnet server that can be run on the nodemcu device. The luatool.py was extended to offer exchangeable transports (serial and tcp) to support all features also via remote telnet sessions.

### CODE REVIEW

**Comment by 4refr0nt** [comment]
Thanks for you work!
Please, increment version number and add change log

**Comment by shing19m** [comment]
Hi Eku,

can you provide your telnet server code? Or try using the telnet server from this project and try again.

Regard
J

**Comment by eku** [comment]
I'm using the telnet server code from the luatool project.

**Comment by shing19m** [comment]
Ok, I am puzzled. 

1) Does the direct telnet list all files you got on the device like directly talking to it via serial port? Or does it also just stop after *name:init.lua, size:468*?

2) I may not matter, but *Welcome to esp1 running NodeMCU!* is not the default welcome message of the supplied telnet server code. Any other modifications?

3) you run the which nodemcu version? I tested with *nodemcu_integer_0.9.6-dev_20150704.bin*

**Comment by eku** [comment]
1) yes, it returns only one line. But the telnet session still responds to further Lua commands.
2) I changed the banner.
3) I'm using the dev branch of nodemcu, i.e. SDK 1.4

**Comment by shing19m** [comment]
can you publish the output of
 * ./luatool/luatool.py --port /dev/**your tty** -l | hexdump -C 
 * ./luatool/luatool.py --ip 192.168.33.131 -l | hexdump -C 
 * echo "local l = file.list();for k,v in pairs(l) do print('name:'..k..', size:'..v)end" | nc -w 1 192.168.33.131 23 | hexdump -C

this might help me a little

**Comment by eku** [comment]
Please find the output at https://gist.github.com/eku/1b018e2f49e98a7b8ada

**Comment by shing19m** [comment]
Hi,

esp-common's updatesrv.lua fails with line *srv:on("receive", onReceive)* because of *method not supported*. So i cannot verify this.

The only clue I got from your files, is that (as in the original code) my code waits for some '>' appear as prompt (either via serial port or socket). The serial port code just continues but the socket code hangs. 

Sadly i cannot reproduce this with my setting here. 

can you try the attached diff? 
```
diff --git a/luatool/luatool.py b/luatool/luatool.py
index 41a01d3..2ce8ec6 100755
--- a/luatool/luatool.py
+++ b/luatool/luatool.py
@@ -144,7 +144,10 @@ class TcpSocketTransport(AbstractTransport):
             sys.stdout.write(" -> send without check")
 
     def read(self, length):
-        return self.socket.recv(length)
+        data = self.socket.recv(length)
+        if not data:
+            return ''
+        return data
 
     def close(self):
         self.socket.close()

```

And, sorry to say, I am a little clue less...

**Comment by eku** [comment]
The latest SDK and NodeMCU dev branch requires a strict event driven programming as discussed in [this NodeMCU issue](https://github.com/nodemcu/nodemcu-firmware/issues/730). This would explain why I see only the first line of the output from the fsinfo test  program.

**Pull request merged**
